# Numpy基础

本章主要讲如何使用Numpy

首先引入numpy库

In [11]:
import numpy as np

在jupyter lab中，如果需要知道numpy有哪些可以用的函数只需要按`Tab`键就能实现自动补全了

如果不知道其中的方法怎么使用，可以在其后面加个问号让其输出帮助信息

In [12]:
np.abs?

Call signature:  np.abs(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'absolute'>
File:            ~/.pyenv/versions/3.6.8/lib/python3.6/site-packages/numpy/__init__.py
Docstring:      
absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the absolute value element-wise.

``np.abs`` is a shorthand for this function.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the 

## Numpy数组

numpy不使用python自带的数组或列表结构，而是使用自建数据结构ndarray作为数组使用

其生成方式有：

### 从已有数据中创建数组

In [13]:
lst1 = [1.34, 2.56, 1., 8.9]
np.array(lst1)

array([1.34, 2.56, 1.  , 8.9 ])

In [14]:
type(np.array(lst1))

numpy.ndarray

### 利用random模块生成随机数组

In [15]:
np.random.random(size=[3, 3])

array([[0.68647097, 0.01014987, 0.53029212],
       [0.60676205, 0.22651369, 0.00808254],
       [0.03756106, 0.1847978 , 0.17385694]])

### 创建特定形状的多维数组

numpy可以生成全零、全一、全空、指定数值的数组，甚至是单位矩阵

In [16]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((2, 3))   ## 注意这里不一定为0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
nd1 = np.zeros((4, 5))
print(nd1)
nd2 = np.ones_like(nd1)
print(nd2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.full((3, 5), 493)

array([[493, 493, 493, 493, 493],
       [493, 493, 493, 493, 493],
       [493, 493, 493, 493, 493]])

### arange、linspace

numpy中的arange个linspace用于生成连续等差数组。两者的生成方式有一定差异

In [22]:
nd1 = np.arange(0, 1, 0.1)
print(nd1)
nd2 = np.linspace(0, 1, 10)
print(nd2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## 从数组中获取数据

ndarray可以跟python的列表一样做切片操作

In [23]:
nd = np.arange(0, 25).reshape(5, -1)
nd

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
nd[0:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
nd[:,2]

array([ 2,  7, 12, 17, 22])

In [26]:
nd[3:,2:]

array([[17, 18, 19],
       [22, 23, 24]])

In [27]:
nd[2::2,::2]   # 切片操作的第三个数字表示间隔

array([[10, 12, 14],
       [20, 22, 24]])

## 数组的算术运算

直接使用加减乘除可以实现逐元素运算

In [28]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [1, 2]])
A*B

array([[1, 2],
       [3, 8]])

或者使用一个ndarray对数字运算，同样也是逐元素的

In [29]:
A*2

array([[2, 4],
       [6, 8]])

### 矩阵运算

ndarray可以使用运算符`@`做矩阵运算

In [30]:
C = np.array([[5, 6, 7], [8, 9, 10]])
A@C

array([[21, 24, 27],
       [47, 54, 61]])

## 数组变形

numpy支持各种数组变形，包括：

+ 重置维度（reshape/resize）
+ 展平（ravel/flatten）
+ 转置（T）
+ 轴对换（transpose）

In [31]:
C.T

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

In [33]:
C.reshape(3, -1)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

其同时也支持数组合并

In [37]:
nd1 = np.array([[1, 2], [3, 4]])
nd2 = np.array([[5, 6]])
np.concatenate((nd1, nd2), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
np.concatenate((nd1, nd2.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [42]:
nd1 = np.array([[1, 2], [3, 4]])
nd2 = np.array([[5, 6], [7, 8]])
np.stack((nd1, nd2), axis = 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
np.stack((nd1, nd2), axis = 1)  # 堆叠的维度不同

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [44]:
np.stack((nd1, nd2), axis = 2)

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

## 通用函数

numpy支持常用数学函数

In [45]:
nd = np.array([2., 3., 4., 5.])
np.sqrt(nd)

array([1.41421356, 1.73205081, 2.        , 2.23606798])

## 广播机制

numpy一般要求参与运算的两个ndarray的shape必须一样。但如果真出现不一样的情况的话其也可以通过广播机制做一些适应。其包括：

+ 自动对齐：让参与运算的ndarray的维度对齐，不足的补1
    + 例如2x3x2的ndarray和3x2的ndarray运算时，后者需要对齐到1x3x2
+ 复制：对比每个维度，如果某个维度两者不相同且其中一者为1，则为1的那个进行复制
    + 例如上例，1x3x2的ndarray就需要自我复制一份补足使其扩充到2x3x2

In [46]:
nd1 = np.arange(0, 40, 10).reshape(4, 1)
nd2 = np.arange(0, 3)
print(nd1)
print(nd2)

[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]


In [47]:
nd1+nd2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

## 总结

numpy的优势在于其可以利用并行计算的优势加速数组计算。

其可以执行的操作包括：

+ 创建数组
+ 获取数组数据
+ 数组间算术运算
+ 数组变形
+ 数学函数运算
+ 广播机制（自动复制）